"""
Comprehensive Taylor Swift catalog data for the constellation view and era theming.
"""

TAYLOR_CATALOG = [
    # Taylor Swift (Debut) - 2006
    {"name": "Tim McGraw", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "Picture to Burn", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Teardrops On My Guitar", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "A Place in This World", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "Cold as You", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "The Outside", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "Tied Together with a Smile", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Stay Beautiful", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Should've Said No", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 9, "is_single": True, "is_vault_track": False},
    {"name": "Mary's Song (Oh My My My)", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Our Song", "album": "Taylor Swift", "era": "Taylor Swift", "track_number": 11, "is_single": True, "is_vault_track": False},

    # Fearless - 2008
    {"name": "Fearless", "album": "Fearless", "era": "Fearless", "track_number": 1, "is_single": False, "is_vault_track": False},
    {"name": "Fifteen", "album": "Fearless", "era": "Fearless", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Love Story", "album": "Fearless", "era": "Fearless", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "Hey Stephen", "album": "Fearless", "era": "Fearless", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "White Horse", "album": "Fearless", "era": "Fearless", "track_number": 5, "is_single": True, "is_vault_track": False},
    {"name": "You Belong With Me", "album": "Fearless", "era": "Fearless", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "Breathe", "album": "Fearless", "era": "Fearless", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Tell Me Why", "album": "Fearless", "era": "Fearless", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "You're Not Sorry", "album": "Fearless", "era": "Fearless", "track_number": 9, "is_single": True, "is_vault_track": False},
    {"name": "The Way I Loved You", "album": "Fearless", "era": "Fearless", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Forever & Always", "album": "Fearless", "era": "Fearless", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "The Best Day", "album": "Fearless", "era": "Fearless", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "Change", "album": "Fearless", "era": "Fearless", "track_number": 13, "is_single": False, "is_vault_track": False},

    # Speak Now - 2010
    {"name": "Mine", "album": "Speak Now", "era": "Speak Now", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "Sparks Fly", "album": "Speak Now", "era": "Speak Now", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Back to December", "album": "Speak Now", "era": "Speak Now", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "Speak Now", "album": "Speak Now", "era": "Speak Now", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "Dear John", "album": "Speak Now", "era": "Speak Now", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "Mean", "album": "Speak Now", "era": "Speak Now", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "The Story of Us", "album": "Speak Now", "era": "Speak Now", "track_number": 7, "is_single": True, "is_vault_track": False},
    {"name": "Never Grow Up", "album": "Speak Now", "era": "Speak Now", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Enchanted", "album": "Speak Now", "era": "Speak Now", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "Better Than Revenge", "album": "Speak Now", "era": "Speak Now", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Innocent", "album": "Speak Now", "era": "Speak Now", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "Haunted", "album": "Speak Now", "era": "Speak Now", "track_number": 12, "is_single": True, "is_vault_track": False},
    {"name": "Last Kiss", "album": "Speak Now", "era": "Speak Now", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "Long Live", "album": "Speak Now", "era": "Speak Now", "track_number": 14, "is_single": False, "is_vault_track": False},

    # Red - 2012
    {"name": "State of Grace", "album": "Red", "era": "Red", "track_number": 1, "is_single": False, "is_vault_track": False},
    {"name": "Red", "album": "Red", "era": "Red", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Treacherous", "album": "Red", "era": "Red", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "I Knew You Were Trouble", "album": "Red", "era": "Red", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "All Too Well", "album": "Red", "era": "Red", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "22", "album": "Red", "era": "Red", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "I Almost Do", "album": "Red", "era": "Red", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "We Are Never Getting Back Together", "album": "Red", "era": "Red", "track_number": 8, "is_single": True, "is_vault_track": False},
    {"name": "Stay Stay Stay", "album": "Red", "era": "Red", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "The Last Time", "album": "Red", "era": "Red", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Holy Ground", "album": "Red", "era": "Red", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "Sad Beautiful Tragic", "album": "Red", "era": "Red", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "The Lucky One", "album": "Red", "era": "Red", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "Everything Has Changed", "album": "Red", "era": "Red", "track_number": 14, "is_single": True, "is_vault_track": False},
    {"name": "Starlight", "album": "Red", "era": "Red", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "Begin Again", "album": "Red", "era": "Red", "track_number": 16, "is_single": True, "is_vault_track": False},
    {"name": "All Too Well (10 Minute Version)", "album": "Red (Taylor's Version)", "era": "Red", "track_number": 30, "is_single": True, "is_vault_track": True},

    # 1989 - 2014
    {"name": "Welcome to New York", "album": "1989", "era": "1989", "track_number": 1, "is_single": False, "is_vault_track": False},
    {"name": "Blank Space", "album": "1989", "era": "1989", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Style", "album": "1989", "era": "1989", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "Out of the Woods", "album": "1989", "era": "1989", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "All You Had to Do Was Stay", "album": "1989", "era": "1989", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "Shake It Off", "album": "1989", "era": "1989", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "I Wish You Would", "album": "1989", "era": "1989", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Bad Blood", "album": "1989", "era": "1989", "track_number": 8, "is_single": True, "is_vault_track": False},
    {"name": "Wildest Dreams", "album": "1989", "era": "1989", "track_number": 9, "is_single": True, "is_vault_track": False},
    {"name": "How You Get the Girl", "album": "1989", "era": "1989", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "This Love", "album": "1989", "era": "1989", "track_number": 11, "is_single": True, "is_vault_track": False},
    {"name": "I Know Places", "album": "1989", "era": "1989", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "Clean", "album": "1989", "era": "1989", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "New Romantics", "album": "1989", "era": "1989", "track_number": 15, "is_single": True, "is_vault_track": False},

    # reputation - 2017
    {"name": "...Ready For It?", "album": "reputation", "era": "reputation", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "End Game", "album": "reputation", "era": "reputation", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "I Did Something Bad", "album": "reputation", "era": "reputation", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "Don't Blame Me", "album": "reputation", "era": "reputation", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "Delicate", "album": "reputation", "era": "reputation", "track_number": 5, "is_single": True, "is_vault_track": False},
    {"name": "Look What You Made Me Do", "album": "reputation", "era": "reputation", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "So It Goes...", "album": "reputation", "era": "reputation", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Gorgeous", "album": "reputation", "era": "reputation", "track_number": 8, "is_single": True, "is_vault_track": False},
    {"name": "Getaway Car", "album": "reputation", "era": "reputation", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "King of My Heart", "album": "reputation", "era": "reputation", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Dancing with Our Hands Tied", "album": "reputation", "era": "reputation", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "Dress", "album": "reputation", "era": "reputation", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "This Is Why We Can't Have Nice Things", "album": "reputation", "era": "reputation", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "Call It What You Want", "album": "reputation", "era": "reputation", "track_number": 14, "is_single": True, "is_vault_track": False},
    {"name": "New Year's Day", "album": "reputation", "era": "reputation", "track_number": 15, "is_single": False, "is_vault_track": False},

    # Lover - 2019
    {"name": "I Forgot That You Existed", "album": "Lover", "era": "Lover", "track_number": 1, "is_single": False, "is_vault_track": False},
    {"name": "Cruel Summer", "album": "Lover", "era": "Lover", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Lover", "album": "Lover", "era": "Lover", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "The Man", "album": "Lover", "era": "Lover", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "The Archer", "album": "Lover", "era": "Lover", "track_number": 5, "is_single": True, "is_vault_track": False},
    {"name": "I Think He Knows", "album": "Lover", "era": "Lover", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "Miss Americana & The Heartbreak Prince", "album": "Lover", "era": "Lover", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Paper Rings", "album": "Lover", "era": "Lover", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Cornelia Street", "album": "Lover", "era": "Lover", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "Death by a Thousand Cuts", "album": "Lover", "era": "Lover", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "London Boy", "album": "Lover", "era": "Lover", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "Soon You'll Get Better", "album": "Lover", "era": "Lover", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "False God", "album": "Lover", "era": "Lover", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "You Need To Calm Down", "album": "Lover", "era": "Lover", "track_number": 14, "is_single": True, "is_vault_track": False},
    {"name": "Afterglow", "album": "Lover", "era": "Lover", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "ME!", "album": "Lover", "era": "Lover", "track_number": 16, "is_single": True, "is_vault_track": False},
    {"name": "It's Nice to Have a Friend", "album": "Lover", "era": "Lover", "track_number": 17, "is_single": False, "is_vault_track": False},
    {"name": "Daylight", "album": "Lover", "era": "Lover", "track_number": 18, "is_single": False, "is_vault_track": False},

    # folklore - 2020
    {"name": "the 1", "album": "folklore", "era": "folklore", "track_number": 1, "is_single": False, "is_vault_track": False},
    {"name": "cardigan", "album": "folklore", "era": "folklore", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "the last great american dynasty", "album": "folklore", "era": "folklore", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "exile", "album": "folklore", "era": "folklore", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "my tears ricochet", "album": "folklore", "era": "folklore", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "mirrorball", "album": "folklore", "era": "folklore", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "seven", "album": "folklore", "era": "folklore", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "august", "album": "folklore", "era": "folklore", "track_number": 8, "is_single": True, "is_vault_track": False},
    {"name": "this is me trying", "album": "folklore", "era": "folklore", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "illicit affairs", "album": "folklore", "era": "folklore", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "invisible string", "album": "folklore", "era": "folklore", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "mad woman", "album": "folklore", "era": "folklore", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "epiphany", "album": "folklore", "era": "folklore", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "betty", "album": "folklore", "era": "folklore", "track_number": 14, "is_single": True, "is_vault_track": False},
    {"name": "peace", "album": "folklore", "era": "folklore", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "hoax", "album": "folklore", "era": "folklore", "track_number": 16, "is_single": False, "is_vault_track": False},
    {"name": "the lakes", "album": "folklore", "era": "folklore", "track_number": 17, "is_single": False, "is_vault_track": False},

    # evermore - 2020
    {"name": "willow", "album": "evermore", "era": "evermore", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "champagne problems", "album": "evermore", "era": "evermore", "track_number": 2, "is_single": False, "is_vault_track": False},
    {"name": "gold rush", "album": "evermore", "era": "evermore", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "'tis the damn season", "album": "evermore", "era": "evermore", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "tolerate it", "album": "evermore", "era": "evermore", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "no body no crime", "album": "evermore", "era": "evermore", "track_number": 6, "is_single": True, "is_vault_track": False},
    {"name": "happiness", "album": "evermore", "era": "evermore", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "dorothea", "album": "evermore", "era": "evermore", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "coney island", "album": "evermore", "era": "evermore", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "ivy", "album": "evermore", "era": "evermore", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "cowboy like me", "album": "evermore", "era": "evermore", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "long story short", "album": "evermore", "era": "evermore", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "marjorie", "album": "evermore", "era": "evermore", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "closure", "album": "evermore", "era": "evermore", "track_number": 14, "is_single": False, "is_vault_track": False},
    {"name": "evermore", "album": "evermore", "era": "evermore", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "right where you left me", "album": "evermore", "era": "evermore", "track_number": 16, "is_single": False, "is_vault_track": False},
    {"name": "it's time to go", "album": "evermore", "era": "evermore", "track_number": 17, "is_single": False, "is_vault_track": False},

    # Midnights - 2022
    {"name": "Lavender Haze", "album": "Midnights", "era": "Midnights", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "Maroon", "album": "Midnights", "era": "Midnights", "track_number": 2, "is_single": False, "is_vault_track": False},
    {"name": "Anti-Hero", "album": "Midnights", "era": "Midnights", "track_number": 3, "is_single": True, "is_vault_track": False},
    {"name": "Snow on the Beach", "album": "Midnights", "era": "Midnights", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "You're On Your Own Kid", "album": "Midnights", "era": "Midnights", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "Midnight Rain", "album": "Midnights", "era": "Midnights", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "Question...?", "album": "Midnights", "era": "Midnights", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Vigilante Shit", "album": "Midnights", "era": "Midnights", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Bejeweled", "album": "Midnights", "era": "Midnights", "track_number": 9, "is_single": True, "is_vault_track": False},
    {"name": "Labyrinth", "album": "Midnights", "era": "Midnights", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Karma", "album": "Midnights", "era": "Midnights", "track_number": 11, "is_single": True, "is_vault_track": False},
    {"name": "Sweet Nothing", "album": "Midnights", "era": "Midnights", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "Mastermind", "album": "Midnights", "era": "Midnights", "track_number": 13, "is_single": False, "is_vault_track": False},
    {"name": "The Great War", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 14, "is_single": False, "is_vault_track": False},
    {"name": "Bigger Than The Whole Sky", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "Paris", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 16, "is_single": False, "is_vault_track": False},
    {"name": "High Infidelity", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 17, "is_single": False, "is_vault_track": False},
    {"name": "Glitch", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 18, "is_single": False, "is_vault_track": False},
    {"name": "Would've, Could've, Should've", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 19, "is_single": False, "is_vault_track": False},
    {"name": "Dear Reader", "album": "Midnights (3am Edition)", "era": "Midnights", "track_number": 20, "is_single": False, "is_vault_track": False},

    # The Tortured Poets Department - 2024
    {"name": "Fortnight", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "The Tortured Poets Department", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 2, "is_single": False, "is_vault_track": False},
    {"name": "My Boy Only Breaks His Favorite Toys", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "Down Bad", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 4, "is_single": True, "is_vault_track": False},
    {"name": "So Long London", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 5, "is_single": False, "is_vault_track": False},
    {"name": "But Daddy I Love Him", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "Fresh Out the Slammer", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Florida!!!", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Guilty as Sin?", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "Who's Afraid of Little Old Me?", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "I Can Fix Him (No Really I Can)", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "loml", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 12, "is_single": False, "is_vault_track": False},
    {"name": "I Can Do It With a Broken Heart", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 13, "is_single": True, "is_vault_track": False},
    {"name": "The Smallest Man Who Ever Lived", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 14, "is_single": False, "is_vault_track": False},
    {"name": "The Alchemy", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 15, "is_single": False, "is_vault_track": False},
    {"name": "Clara Bow", "album": "The Tortured Poets Department", "era": "The Tortured Poets Department", "track_number": 16, "is_single": False, "is_vault_track": False},
    {"name": "The Black Dog", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 17, "is_single": True, "is_vault_track": False},
    {"name": "imgonnagetyouback", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 18, "is_single": False, "is_vault_track": False},
    {"name": "The Albatross", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 19, "is_single": False, "is_vault_track": False},
    {"name": "Chloe or Sam or Sophia or Marcus", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 20, "is_single": False, "is_vault_track": False},
    {"name": "How Did It End?", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 21, "is_single": False, "is_vault_track": False},
    {"name": "So High School", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 22, "is_single": False, "is_vault_track": False},
    {"name": "I Hate It Here", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 23, "is_single": False, "is_vault_track": False},
    {"name": "thanK you aIMee", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 24, "is_single": True, "is_vault_track": False},
    {"name": "I Look in People's Windows", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 25, "is_single": False, "is_vault_track": False},
    {"name": "The Prophecy", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 26, "is_single": False, "is_vault_track": False},
    {"name": "Cassandra", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 27, "is_single": False, "is_vault_track": False},
    {"name": "Peter", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 28, "is_single": False, "is_vault_track": False},
    {"name": "The Bolter", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 29, "is_single": False, "is_vault_track": False},
    {"name": "Robin", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 30, "is_single": False, "is_vault_track": False},
    {"name": "The Manuscript", "album": "The Tortured Poets Department: The Anthology", "era": "The Tortured Poets Department", "track_number": 31, "is_single": False, "is_vault_track": False},

    # The Life Of A Showgirl - 2025
    {"name": "The Fate of Ophelia", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 1, "is_single": True, "is_vault_track": False},
    {"name": "Elizabeth Taylor", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 2, "is_single": True, "is_vault_track": False},
    {"name": "Opalite", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 3, "is_single": False, "is_vault_track": False},
    {"name": "Father Figure", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 4, "is_single": False, "is_vault_track": False},
    {"name": "Eldest Daughter", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 5, "is_single": True, "is_vault_track": False},
    {"name": "Ruin The Friendship", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 6, "is_single": False, "is_vault_track": False},
    {"name": "Actually Romantic", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 7, "is_single": False, "is_vault_track": False},
    {"name": "Wi$h Li$t", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 8, "is_single": False, "is_vault_track": False},
    {"name": "Wood", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 9, "is_single": False, "is_vault_track": False},
    {"name": "Cancelled!", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 10, "is_single": False, "is_vault_track": False},
    {"name": "Honey", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 11, "is_single": False, "is_vault_track": False},
    {"name": "The Life of a Showgirl", "album": "The Life Of A Showgirl", "era": "The Life Of A Showgirl", "track_number": 12, "is_single": True, "is_vault_track": False},
]


ERA_THEMES = {
    "Taylor Swift": {
        "colors": {"primary": "#8B7355", "secondary": "#C4A882", "accent": "#4A7C59", "bg": "#1a1510"},
        "description": "Where it all began — country roads and teenage dreams",
        "year": 2006,
        "aesthetic": "country",
    },
    "Fearless": {
        "colors": {"primary": "#D4AF37", "secondary": "#FFD700", "accent": "#FFF8DC", "bg": "#1a1608"},
        "description": "Golden and fearless — the fairy tale era",
        "year": 2008,
        "aesthetic": "golden",
    },
    "Speak Now": {
        "colors": {"primary": "#7B2D8E", "secondary": "#9B59B6", "accent": "#D8B4FE", "bg": "#150a1a"},
        "description": "Purple prose and midnight confessions",
        "year": 2010,
        "aesthetic": "enchanted",
    },
    "Red": {
        "colors": {"primary": "#8B0000", "secondary": "#DC143C", "accent": "#FF6B6B", "bg": "#1a0808"},
        "description": "Autumn leaves and burning bridges",
        "year": 2012,
        "aesthetic": "autumn",
    },
    "1989": {
        "colors": {"primary": "#5B9BD5", "secondary": "#87CEEB", "accent": "#E8D5F5", "bg": "#0a1520"},
        "description": "Polaroids and city lights — pop revolution",
        "year": 2014,
        "aesthetic": "polaroid",
    },
    "reputation": {
        "colors": {"primary": "#2D2D2D", "secondary": "#4A4A4A", "accent": "#C0C0C0", "bg": "#0a0a0a"},
        "description": "Snakes and newspapers — the dark era",
        "year": 2017,
        "aesthetic": "dark",
    },
    "Lover": {
        "colors": {"primary": "#FF69B4", "secondary": "#FFB6C1", "accent": "#87CEEB", "bg": "#1a0a15"},
        "description": "Cotton candy skies and kaleidoscope love",
        "year": 2019,
        "aesthetic": "pastel",
    },
    "folklore": {
        "colors": {"primary": "#708090", "secondary": "#A9A9A9", "accent": "#D3D3C7", "bg": "#0f1210"},
        "description": "Cardigan weather and whispered stories in the woods",
        "year": 2020,
        "aesthetic": "forest",
    },
    "evermore": {
        "colors": {"primary": "#8B6914", "secondary": "#B8860B", "accent": "#DAA520", "bg": "#12100a"},
        "description": "Rust and amber — the eternal autumn",
        "year": 2020,
        "aesthetic": "rust",
    },
    "Midnights": {
        "colors": {"primary": "#191970", "secondary": "#4169E1", "accent": "#E6E6FA", "bg": "#08081a"},
        "description": "3AM confessions under lavender haze",
        "year": 2022,
        "aesthetic": "midnight",
    },
    "The Tortured Poets Department": {
        "colors": {"primary": "#8B8378", "secondary": "#C4B5A5", "accent": "#DDD0C0", "bg": "#14120f"},
        "description": "Ink-stained pages and phantom pain",
        "year": 2024,
        "aesthetic": "parchment",
    },
    "The Life Of A Showgirl": {
        "colors": {"primary": "#C41E3A", "secondary": "#FF6B81", "accent": "#FFD700", "bg": "#1a0a0e"},
        "description": "Spotlight, sequins, and the price of the show",
        "year": 2025,
        "aesthetic": "showgirl"
    },
}
